# based partly on https://github.com/r-lib/actions/blob/master/examples/check-full.yaml

on: 
  push:
    branches:
      - check-release
      - check-devel
  pull_request:
    branches:
      - master
      
name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: macOS-latest, r: 'devel' }
          - {os: macOS-latest, r: '3.6'}
 	        #- {os: ubuntu-16.04, r: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest" }
 	        #- {os: windows-latest, r: 'devel' }
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.conig.cran }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
          
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install Rcpp from github
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_github('RcppCore/Rcpp')"

      - name: Install BiocManager
        run: Rscript -e "remotes::install_cran('BiocManager')"
        
      - name: Install this package and dependencies
        run: Rscript -e "BiocManager::install('epivizr', dependencies=TRUE)"
        
      - name: Install rcmdcheck
        run: Rscript -e "remotes::install_cran('rcmdcheck')"
 
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(build_args = c('--keep-empty-dirs', '--no-resave-data'), args=c('--no-vignettes', '--timings'), error_on = 'error')"
          

